-- Q.11.Calculate the percentage contribution of each pizza type to total revenue.

WITH
	TOTAL_REVENUE AS (
		SELECT
			PIZZA_TYPES.CATEGORY,
			SUM(ORDER_DETAILS.QUANTITY * PIZZAS.PRICE) AS REVENUE
		FROM
			PIZZA_TYPES
			JOIN PIZZAS ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
			JOIN ORDER_DETAILS ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
		GROUP BY
			PIZZA_TYPES.CATEGORY
	)
SELECT
	CATEGORY,
	ROUND(
		REVENUE * 100.0 / (
			SELECT
				SUM(REVENUE)
			FROM
				TOTAL_REVENUE
		),
		0
	) AS PERCENTAGE_CONTRIBUTION
FROM
	TOTAL_REVENUE
ORDER BY
	PERCENTAGE_CONTRIBUTION DESC;