-- Q.12. Analyze the cumulative revenue generated over time.

WITH
	DAILY_REVENUE AS (
		SELECT
			ORDERS.DATE,
			SUM(ORDER_DETAILS.QUANTITY * PIZZAS.PRICE) AS REVENUE
		FROM
			ORDERS
			JOIN ORDER_DETAILS ON ORDERS.ORDER_ID = ORDER_DETAILS.ORDER_ID
			JOIN PIZZAS ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
		GROUP BY
			ORDERS.DATE
	)
SELECT
	DATE,
	REVENUE,
	SUM(REVENUE) OVER (
		ORDER BY
			DATE
	) AS CUMULATIVE_REVENUE
FROM
	DAILY_REVENUE;