-- Q.4. Identify the most common pizza size ordered.

SELECT
	PIZZAS.SIZE,
	COUNT(ORDER_DETAILS.QUANTITY) AS COMMON_PIZZA_ORDERED
FROM
	ORDER_DETAILS
	JOIN PIZZAS ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
GROUP BY
	PIZZAS.SIZE
ORDER BY
	COMMON_PIZZA_ORDERED DESC
LIMIT
	1;