--Q.2. Calculate the total revenue generated from pizza sales.


SELECT
	ROUND(SUM(ORDER_DETAILS.QUANTITY * PIZZAS.PRICE), 0) AS TOTAL_REVENUE
FROM
	ORDER_DETAILS
	JOIN PIZZAS ON PIZZAS.PIZZA_ID = ORDER_DETAILS.PIZZA_ID