-- Q.3. Identify the highest-priced pizza.

SELECT
	PIZZA_TYPES.NAME,
	PIZZAS.PRICE
FROM
	PIZZA_TYPES
	JOIN PIZZAS ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
GROUP BY
	PIZZA_TYPES.NAME,
	PIZZAS.PRICE
ORDER BY
	PIZZAS.PRICE DESC
LIMIT
	1;